import type { AnimeTheme } from './types';

const rawThemes: Array<[string, string[], string, string, string[]]> = [
  ['Dragon Ball', ['Goku', 'Vegeta', 'Gohan'], 'Surpass yesterday with calm power.', '⚡', ['#00BFFF', '#CFEFFF', '#F7FBFF']],
  ['Naruto', ['Naruto Uzumaki', 'Sasuke Uchiha', 'Kakashi Hatake'], 'Your discipline is your will of fire.', '🍥', ['#FF9F1C', '#00BFFF', '#101828']],
  ['One Piece', ['Luffy', 'Zoro', 'Nami'], 'A dream needs a map and daily courage.', '🏴‍☠️', ['#E63946', '#00B4D8', '#F1FAEE']],
  ['Attack on Titan', ['Eren Yeager', 'Mikasa Ackerman', 'Armin Arlert'], 'Advance one wall at a time.', '🛡️', ['#9A8C98', '#22223B', '#F2E9E4']],
  ['Demon Slayer', ['Tanjiro Kamado', 'Nezuko Kamado', 'Zenitsu Agatsuma'], 'Breathe, focus, cut through resistance.', '🌊', ['#2EC4B6', '#E71D36', '#FDFFFC']],
  ['Jujutsu Kaisen', ['Yuji Itadori', 'Megumi Fushiguro', 'Nobara Kugisaki'], 'Turn pressure into cursed-energy control.', '👁️', ['#6C63FF', '#00D1FF', '#0B1026']],
  ['Bleach', ['Ichigo Kurosaki', 'Rukia Kuchiki', 'Renji Abarai'], 'Protect your future with every rep.', '🗡️', ['#FF6B35', '#F7F7FF', '#101010']],
  ['Hunter x Hunter', ['Gon Freecss', 'Killua Zoldyck', 'Kurapika'], 'Curiosity plus training becomes mastery.', '🎣', ['#74D680', '#7BDFF2', '#F7D6E0']],
  ['Death Note', ['Light Yagami', 'L', 'Misa Amane'], 'Strategy wins before effort begins.', '📓', ['#F8F9FA', '#111827', '#C1121F']],
  ['Vinland Saga', ['Thorfinn', 'Canute', 'Askeladd'], 'Build peace through relentless discipline.', '🪓', ['#A7C957', '#386641', '#F2E8CF']],
  ['Blue Lock', ['Isagi Yoichi', 'Bachira Meguru', 'Rin Itoshi'], 'Awaken your exam ego with precision.', '⚽', ['#00BFFF', '#1D4ED8', '#F8FAFC']],
  ['Solo Leveling', ['Sung Jinwoo', 'Cha Hae-In', 'Igris'], 'Arise after every failed session.', '👑', ['#8B5CF6', '#111827', '#38BDF8']],
  ['Tokyo Ghoul', ['Ken Kaneki', 'Touka Kirishima', 'Hideyoshi Nagachika'], 'Transform pain into controlled growth.', '☕', ['#EF4444', '#111827', '#D1D5DB']],
  ['Haikyuu', ['Hinata Shoyo', 'Tobio Kageyama', 'Kei Tsukishima'], 'Small jumps become impossible heights.', '🏐', ['#F97316', '#111827', '#F8FAFC']],
  ['Chainsaw Man', ['Denji', 'Power', 'Aki Hayakawa'], 'Cut through procrastination now.', '🪚', ['#F59E0B', '#DC2626', '#111827']],
  ['Black Clover', ['Asta', 'Yuno', 'Noelle Silva'], 'No talent? Then outwork fate.', '🍀', ['#22C55E', '#111827', '#E0F2FE']],
  ['My Hero Academia', ['Izuku Midoriya', 'Katsuki Bakugo', 'Ochaco Uraraka'], 'Go beyond your comfort zone.', '💥', ['#22C55E', '#F97316', '#1E3A8A']],
  ['Fullmetal Alchemist', ['Edward Elric', 'Alphonse Elric', 'Winry Rockbell'], 'Equivalent exchange: effort becomes results.', '⚙️', ['#D97706', '#64748B', '#F8FAFC']],
  ['Steins Gate', ['Rintaro Okabe', 'Kurisu Makise', 'Mayuri Shiina'], 'Control time before time controls you.', '⏱️', ['#7C2D12', '#0F172A', '#FDE68A']],
  ['Code Geass', ['Lelouch Lamperouge', 'C.C.', 'Suzaku Kururugi'], 'Command your day like a strategist.', '♟️', ['#7C3AED', '#111827', '#F9FAFB']],
  ['Re Zero', ['Subaru Natsuki', 'Emilia', 'Rem'], 'Restart stronger; loops are lessons.', '🔁', ['#A78BFA', '#DBEAFE', '#111827']],
  ['Spy x Family', ['Anya Forger', 'Loid Forger', 'Yor Forger'], 'Balance mission, mind, and heart.', '🕵️', ['#F9A8D4', '#86EFAC', '#111827']],
  ['Mob Psycho', ['Shigeo Kageyama', 'Reigen Arataka', 'Ritsu Kageyama'], 'Quiet consistency reaches 100%.', '🌀', ['#A3E635', '#22D3EE', '#111827']],
  ['Dr Stone', ['Senku Ishigami', 'Chrome', 'Kohaku'], 'Science your way to better habits.', '🧪', ['#22C55E', '#F8FAFC', '#0F172A']],
  ['JoJo', ['Jotaro Kujo', 'Joseph Joestar', 'Josuke Higashikata'], 'Pose with confidence. Execute with grit.', '⭐', ['#C084FC', '#F472B6', '#FACC15']],
  ['Fire Force', ['Shinra Kusakabe', 'Arthur Boyle', 'Maki Oze'], 'Ignite focus. Extinguish excuses.', '🔥', ['#F97316', '#DC2626', '#111827']],
  ['Fairy Tail', ['Natsu Dragneel', 'Lucy Heartfilia', 'Erza Scarlet'], 'Your guild is your routine.', '🐉', ['#EF4444', '#60A5FA', '#FDE68A']],
  ['Sword Art Online', ['Kirito', 'Asuna', 'Sinon'], 'Clear today’s floor.', '🕹️', ['#38BDF8', '#111827', '#F8FAFC']],
  ['Bungou Stray Dogs', ['Atsushi Nakajima', 'Osamu Dazai', 'Doppo Kunikida'], 'Write the chapter you want to live.', '📚', ['#F59E0B', '#1F2937', '#F8FAFC']],
  ['Classroom of the Elite', ['Kiyotaka Ayanokoji', 'Suzune Horikita', 'Kikyo Kushida'], 'Win quietly through systems.', '🏫', ['#60A5FA', '#111827', '#E5E7EB']],
  ['Frieren', ['Frieren', 'Fern', 'Stark'], 'Long journeys are built calmly.', '🪄', ['#A7F3D0', '#C4B5FD', '#111827']],
  ['Cowboy Bebop', ['Spike Spiegel', 'Faye Valentine', 'Jet Black'], 'Flow smooth, work sharp.', '🎷', ['#F59E0B', '#2563EB', '#111827']],
  ['Slam Dunk', ['Hanamichi Sakuragi', 'Kaede Rukawa', 'Takenori Akagi'], 'Repetition turns clumsy into clutch.', '🏀', ['#DC2626', '#F97316', '#F8FAFC']],
  ['Kuroko no Basket', ['Tetsuya Kuroko', 'Taiga Kagami', 'Ryota Kise'], 'Invisible habits create visible wins.', '⛹️', ['#38BDF8', '#EF4444', '#F8FAFC']],
  ['Your Name', ['Mitsuha Miyamizu', 'Taki Tachibana', 'Sayaka Natori'], 'Meet your future through today’s effort.', '☄️', ['#38BDF8', '#F472B6', '#111827']],
  ['Weathering With You', ['Hodaka Morishima', 'Hina Amano', 'Nagi Amano'], 'Find sunlight inside disciplined storms.', '🌦️', ['#60A5FA', '#FDE68A', '#F8FAFC']],
  ['Neon Genesis Evangelion', ['Shinji Ikari', 'Rei Ayanami', 'Asuka Langley'], 'Pilot the day despite fear.', '🤖', ['#A3E635', '#7C3AED', '#111827']],
  ['Gintama', ['Gintoki Sakata', 'Shinpachi Shimura', 'Kagura'], 'Laugh, recover, then strike again.', '🍡', ['#93C5FD', '#F8FAFC', '#111827']],
  ['The Promised Neverland', ['Emma', 'Norman', 'Ray'], 'Plan intelligently. Move decisively.', '🧩', ['#F97316', '#111827', '#F8FAFC']],
  ['Made in Abyss', ['Riko', 'Reg', 'Nanachi'], 'Descend into hard topics bravely.', '🕳️', ['#A3E635', '#92400E', '#F8FAFC']],
  ['Toradora', ['Taiga Aisaka', 'Ryuuji Takasu', 'Minori Kushieda'], 'Tame chaos with tiny rituals.', '🐯', ['#F97316', '#F9A8D4', '#111827']],
  ['Kaguya-sama', ['Kaguya Shinomiya', 'Miyuki Shirogane', 'Chika Fujiwara'], 'Win the mind game against delay.', '💌', ['#EF4444', '#F8FAFC', '#111827']],
  ['Violet Evergarden', ['Violet Evergarden', 'Claudia Hodgins', 'Cattleya Baudelaire'], 'Make every note meaningful.', '✉️', ['#C4B5FD', '#DBEAFE', '#111827']],
  ['Nana', ['Nana Osaki', 'Nana Komatsu', 'Yasu'], 'Dreams need rhythm and boundaries.', '🎸', ['#EF4444', '#111827', '#F8FAFC']],
  ['Monster', ['Kenzo Tenma', 'Nina Fortner', 'Wolfgang Grimmer'], 'Do the right work, patiently.', '🧠', ['#64748B', '#111827', '#F8FAFC']],
  ['Parasyte', ['Shinichi Izumi', 'Migi', 'Satomi Murano'], 'Adapt without losing your purpose.', '🧬', ['#22C55E', '#111827', '#F8FAFC']],
  ['Erased', ['Satoru Fujinuma', 'Kayo Hinazuki', 'Airi Katagiri'], 'Save tomorrow by acting today.', '⏳', ['#60A5FA', '#F8FAFC', '#111827']],
  ['Mushoku Tensei', ['Rudeus Greyrat', 'Eris Boreas', 'Roxy Migurdia'], 'Rebuild yourself through practice.', '📜', ['#22C55E', '#A78BFA', '#111827']],
  ['Noragami', ['Yato', 'Hiyori Iki', 'Yukine'], 'Small offerings become divine momentum.', '⛩️', ['#38BDF8', '#F8FAFC', '#111827']],
  ['Akira', ['Kaneda', 'Tetsuo', 'Kei'], 'Harness intensity before it controls you.', '🏍️', ['#EF4444', '#FACC15', '#111827']]
];

export const animeThemes: AnimeTheme[] = rawThemes.map(([anime, characters, quote, icon, colors]) => ({
  id: anime.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, ''),
  anime,
  characters,
  quote,
  icon,
  colors,
  effect: `${anime} aura loading pulse`
}));
